### ISSUE TITLE
strtotime for custome time

### ISSUE THREAD

**Issue by 2505rathod** [blaxmas/date-util#3]
how to convert custom time in to strtotime?

**Comment by blaxmas** [comment]
Can't understand what you want. If you want todays 11:00 try:
var str_time = new Date('2016-12-03 11:00')

**Comment by 2505rathod** [comment]
how to convert custom time in to strtotime?

**Comment by blaxmas** [comment]
If you want to add hours to your date object, try:
var str_time = new Date().strtotime('+11 hours');
